.\" Manpage for wiki.
.\" Contact fredrik.wallgren@gmail.com to correct errors or typos.
.TH man 1 "01 Oct 2015" "1.0.0" "wiki man page"
.SH NAME
wiki \- get excerpts from MediaWiki wikis e.g. Wikipedia
.SH SYNOPSIS
.B wiki
[OPTIONS] query
.SH DESCRIPTION
.B wiki
get excerpts from MediaWiki wikis that has the API running.
Default wiki is Wikipedia.
Use the language flag `-l` to get excerpts in any language 
supported by the wiki. Default language is English (en).
.SH OPTIONS
.TP
.BR \-l " " \fR \fILANGUAGE\fR
Fetch articles in language. The language is added to the URL of the API.
For Wikipedia the language string used is the ISO 639-1 code.
For Swedish it is sv and for English en and so on.
.TP
.BR \-n 
Disables the color in output.
.TP
.BR \-no-check-certificate 
Disables the security check of certificates.
You can use this to bypass self signed certificates on your wiki.
.TP
.BR \-s 
Simple output. Only the excerpt is outputted, no information about
redirects or a link to the page is outputted.
.TP
.BR \-short 
Short output. Only the first line of the excerpt is outputted, no information 
about redirects or a link to the page is outputted.
.TP
.BR \-u " " \fR \fIURL\fR
The URL to the API. Defaults to Wikipedias API URL.
The language selected with the -l flag can be interpolated in the URL by
supplying a `%s` in the url. 
E.g. https://%s.wikipedia.org/w/api.php The %s is substituted with 
the language selected with the -l flag.
.TP
.BR \-h 
Outputs help information and exists
.TP
.BR \-version "
Outputs version information and exists
.SH AUTHOR
Fredrik Wallgren (fredrik.wallgren@gmail.com)
